# Generated by Django 5.2 on 2025-05-10 08:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IFL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания заявки')),
                ('fio', models.CharField(help_text='Введите свое имя', max_length=40, verbose_name='ФИО')),
                ('birth_date', models.DateField(default='1900-01-01', verbose_name='Дата рождения')),
                ('phone', models.CharField(default='', max_length=11, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(11)], verbose_name='Телефон')),
                ('email', models.EmailField(default='', max_length=254)),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН (для ЮЛ)')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Имущество физ лиц',
            },
        ),
        migrations.CreateModel(
            name='KASKO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания заявки')),
                ('fio', models.CharField(help_text='Введите свое имя', max_length=40, verbose_name='ФИО')),
                ('birth_date', models.DateField(default='1900-01-01', verbose_name='Дата рождения')),
                ('phone', models.CharField(default='', max_length=11, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(11)], verbose_name='Телефон')),
                ('email', models.EmailField(default='', max_length=254)),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН (для ЮЛ)')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('mark', models.CharField(max_length=40, verbose_name='Марка авто')),
                ('model', models.CharField(max_length=40, verbose_name='Модель авто')),
                ('year', models.DateField(default='1900-01-01', null=True, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Год выпуска/постройки')),
                ('bank', models.CharField(max_length=40, verbose_name='Кредитующий банк')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name_plural': 'КАСКО',
            },
        ),
        migrations.CreateModel(
            name='Klezh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания заявки')),
                ('fio', models.CharField(help_text='Введите свое имя', max_length=40, verbose_name='ФИО')),
                ('birth_date', models.DateField(default='1900-01-01', verbose_name='Дата рождения')),
                ('phone', models.CharField(default='', max_length=11, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(11)], verbose_name='Телефон')),
                ('email', models.EmailField(default='', max_length=254)),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН (для ЮЛ)')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Клещ',
            },
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания заявки')),
                ('fio', models.CharField(help_text='Введите свое имя', max_length=40, verbose_name='ФИО')),
                ('birth_date', models.DateField(default='1900-01-01', verbose_name='Дата рождения')),
                ('phone', models.CharField(default='', max_length=11, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(11)], verbose_name='Телефон')),
                ('email', models.EmailField(default='', max_length=254)),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН (для ЮЛ)')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('bank', models.CharField(max_length=40, verbose_name='Кредитующий банк')),
                ('type_build', models.CharField(choices=[('flat', 'Квартира'), ('residence', 'Жилой дом'), ('apartment', 'Апартаменты')], default='flat', max_length=20, verbose_name='Строение')),
                ('year', models.DateField(default='1900-01-01', null=True, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Год выпуска/постройки')),
                ('risk', models.CharField(choices=[('Structural_elements', 'Конструктивные элементы'), ('interior_decoration', 'Внутренняя отделка и инженерное оборудование'), ('household_property', 'Домашнее имущество')], default='Structural_elements', max_length=50, verbose_name='Объекта страхования')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name_plural': 'Ипотека',
            },
        ),
        migrations.CreateModel(
            name='NS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания заявки')),
                ('fio', models.CharField(help_text='Введите свое имя', max_length=40, verbose_name='ФИО')),
                ('birth_date', models.DateField(default='1900-01-01', verbose_name='Дата рождения')),
                ('phone', models.CharField(default='', max_length=11, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(11)], verbose_name='Телефон')),
                ('email', models.EmailField(default='', max_length=254)),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН (для ЮЛ)')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Несчастный случай',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Ожидает'), (2, 'Обработана'), (3, 'Застрахован'), (4, 'Отказ')], default=1, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': 'Статус заявки',
            },
        ),
        migrations.CreateModel(
            name='OSAGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания заявки')),
                ('fio', models.CharField(help_text='Введите свое имя', max_length=40, verbose_name='ФИО')),
                ('birth_date', models.DateField(default='1900-01-01', verbose_name='Дата рождения')),
                ('phone', models.CharField(default='', max_length=11, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(11)], verbose_name='Телефон')),
                ('email', models.EmailField(default='', max_length=254)),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН (для ЮЛ)')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('mark', models.CharField(max_length=40, verbose_name='Марка авто')),
                ('model', models.CharField(max_length=40, verbose_name='Модель авто')),
                ('year', models.DateField(default='1900-01-01', null=True, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Год выпуска/постройки')),
            ],
            options={
                'verbose_name_plural': 'ОСАГО',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('osago', 'ОСАГО'), ('ns', 'Несчастный случай'), ('klezh', 'Клещ'), ('mortgage', 'Ипотека'), ('KASKO', 'КАСКО'), ('IFL', 'Имущество физических лиц')], default='osago', max_length=50, verbose_name='Продукты')),
            ],
            options={
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
