# Generated by Django 5.2 on 2025-05-10 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PSB_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klezh',
            name='text',
        ),
    ]
